config/routes.rb
Rails.application.routes.draw do
  
devise_for :clients, :controllers => { :omniauth_callbacks => "omniauth_callbacks" }
   

  root 'welcome#index'
  
  resources :products
  resources :donate
  resources :customer

     get 'homepage' => 'welcome#home'
     get 'myinfo' => 'welcome#myinfo'
     

     resources :welcome

end

app/models/welcome.rb
class Welcome < ActiveRecord::Base

def paypal_url(return_url) 
  values = { 
  :business => 'engrohitjain5-facilitator@gmail.com',
  :cmd => '_cart',
  :upload => 1,
  :return => return_url,
  }         # For test transactions use this URL
  "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
end 

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  	@current_client_email = current_client.email if client_signed_in?
    @current_client = current_client
    
  end
  
  

  def home
  end
  def myinfo
  	@client_id = Client.find(parms[:client_id])

    respond_to do |format|      
      
      format.html    
      format.json 
    end
    
  end

def edit
  @client_id = Client.find(parms[:client_id])  
  respond_to do |format|
      
      format.html    
      format.json 
    end 
end

  
  def show

     @client = Client.find(current_client.id)  

     # redirect_to @client.paypal_url(client_registration_path(@client))
     # redirect_to root_url
  end
  
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/welcome/_edit.html.erb
this is edit form

app/views/welcome/_myinfo.html.erb
partial
<br>this is my information
<%= @client_id %>asdfasdf

app/views/welcome/edit.js.erb
$('#edit').html('<%= escape_javascript(render :partial=> edit)%>')


// $("#myinfo").append("<%= escape_javascript(render :partial => welcome/myinfo).html_safe %>");

app/views/welcome/index.html.erb
	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.1/jquery.min.js"></script>
    <script src="http://maxcdn.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
  

      <script type="text/javascript">
            $(document).on('click', '.myinfo', function(){
            $.ajax({
              url: 'welcome/myinfo',
              type: 'GET',
              data:{
                client_id: $('#client_id').val()
                
              },
              success: function (result) {
                alert($('#client_id').val());
                
                
              }
            })
          })







          $(document).on('click', '.edit', function(){
            $.ajax({
                url: '/welcome/edit',
                type: "GET",
              
              data:{
                client_id: $('#client_id').val()
                
              },
              success: function (result) {
                alert($('#client_id').val());
              }
            })
          })


      </script>
      
<% if !(signed_in?) %>
<div>
<center>
      <%= link_to "Registraion For Donation", new_customer_path , class: "btn btn-success"  %>
    </center
    <br><br>
    <center>
      <%= link_to "Registraion", new_client_registration_path , class: "btn btn-success"  %>
    </center>
  
    
    <center>
      <%= link_to "Login", new_client_session_path , class: "btn btn-success" %>
  </center>
    
    <div class="container">
        <div class="dropdown">
        		<button class="btn btn-primary dropdown-toggle" type="button" id="menu1" data-toggle="dropdown">Social
        			<span class="caret"></span>
        		</button>
        		<ul class="dropdown-menu" role="menu" aria-labelledby="menu1">
      				    <li role="presentation">	<%= link_to "Login-with-facebook", client_omniauth_authorize_path(:facebook) , class: "btn btn-primary" %>
	 					  </li>
				          <li role="presentation">	<%= link_to "Sign in with Linkedin", client_omniauth_authorize_path(:linkedin),class: "btn btn-primary" %>
				          </li>
          					<li role="presentation">	<%= link_to "Sign in with Twitter", client_omniauth_authorize_path(:twitter),class: "btn btn-primary"%>
	 						</li>
          					<li role="presentation"></li>
          					<li role="presentation" class="divider"><%= link_to "Sign in with Google", client_omniauth_authorize_path(:google_oauth2),class: "btn btn-primary" %></center>
							</li>
<!--      					     <li role="presentation"><%= link_to "Sign in with PayPal", client_omniauth_authorize_path(:paypal) , class: "btn btn-success" %></li>
 -->
        				</ul>
      				</div>
    			</div><%#= link_to "Sign in with Twitter", '#',class: "btn btn-primary"%>
			</div>
		<div>
	</div>
	<div>

		
      				    <center><%= link_to "Login-with-facebook", client_omniauth_authorize_path(:facebook) , class: "btn btn-primary" %></center>
	 					
				        <center><%= link_to "Sign in with Linkedin", client_omniauth_authorize_path(:linkedin),class: "btn btn-primary" %></center>
				        
          				<center><%= link_to "Sign in with Twitter", client_omniauth_authorize_path(:twitter),class: "btn btn-primary"%></center>
	 					
          				<center>
          				<%= link_to "Sign in with Google", client_omniauth_authorize_path(:google_oauth2),class: "btn btn-primary" %></center>
							<center>
     					    <%= link_to "Login", new_client_session_path , class: "btn btn-success" %></center>
                  <br>
                  <br>
                  
        

	</div>
<% else %>


            <center>
            <div id="myinfo">
              wait for inforatmation
            </div>

              <%= hidden_field_tag :client_id, current_client.id %>
                
                <%= link_to "MyInfo", 'javascript:void(0)', class: 'myinfo' %>
            </center>


            <center>
            <div id="edit">
              wait for Edit
            </div>

              <%= hidden_field_tag :client_id, current_client.id %>
                
                <%= link_to "Edit", 'javascript:void(0)', class: 'edit' %>
            </center>


            




	Hello, <%= @current_client_email %>,<%= @current_client.id%>
	<br>

 		<center>
			<%= link_to "Logout", destroy_client_session_path , method: "delete", class: "btn btn-success" %>
		</center>

  <center>
    <%= link_to "Donation", customer_path(@current_client.id),class: "btn btn-primary" %>
  </center>

 <!--     <%@price_temp=250%>
<%#= form_for Donate.new ,url: donate_index_path(@donate), method: :post do |f| %>
      <%#f.hidden_field :client_id, :value => @current_client.id %>
      <%# f.hidden_field :price, :value => @price_temp %>

      <%#= f.submit "Donation(250)(INR)" %>
<%# end %> -->

      <%#= link_to "Donation(250)", donate_index_path(@donate,:client_id => current_client.id,:price => 250),:method=> :post,class: "btn btn-primary" %>
      <!-- https://www.sandbox.paypal.com/home -->







    
<% end %>


<center><h1>Welcome to facebook/linkedin/Twittor/google Api Integration</h1></center>

app/views/welcome/myinfo.js.erb
// $('#myinfo').html('<%= escape_javascript(render :partial=> myinfo)%>')

// $("#myinfo").alert("From myinfo");
// $("#myinfo").append("<%= escape_javascript(render :partial => welcome/myinfo).html_safe %>");


$("#myinfo").html("<b>hello from js file</b>")

app/views/welcome/show.html.erb
adfsdfasdf